### ISSUE TITLE
Krastorio 2 base uses always best assembling machine for copper cable

### ISSUE THREAD

**Issue by T3rm1** [factoriolab/factorio-lab#282] opened 2020-11-22 18:41 UTC
It can't be changed.
![image](https://user-images.githubusercontent.com/5060247/99913926-a5339780-2cfa-11eb-9c36-62ffff363a5b.png)

**Comment by dcbroad3** [comment] 2020-11-23 15:05
It looks like there are two recipes for copper cable in Krastorio 2. One uses copper plates and one uses copper ore. It looks as though you have disabled the recipe that takes copper plates, and the calculator is using the recipe that takes copper ore. Now I'm not sure whether this is correct, but the calculator thinks that recipe is only allowed in the advanced assembly machine, so it isn't giving you the option to change it. The copper plate based recipe does allow you to change the assembly machine.

If you click the arrow to the left of that row, and go to the "Recipes" tab, are all of the recipes enabled? (If they are greyed out they are disabled) Do you know whether both of these recipes should actually be allowed in all assembling machines?

**Comment by T3rm1** [comment] 2020-11-23 16:45
Both were enabled. Good hint though. I'm not in late game so I don't know anything about the advanced assembling machine. I was able to solve my problem by disabling the ore-to-cable recipe. I think it makes sense that only the advanced assembling machine can process the ore directly.

**Comment by dcbroad3** [comment] 2020-11-29 04:07
I'm going to close this issue since the app is working as designed here, but if there's something you think could be done to handle this situation better please let me know.

**Closed by dcbroad3** 2020-11-29 04:07 UTC
Labels: bug
