### ISSUE TITLE
Preset scroll bar in the recipe list

### ISSUE THREAD

**Issue by Kazmodah** [factoriolab/factorio-lab#197] opened 2020-09-19 08:50 UTC
**Describe the bug**

**To Reproduce**
1. Go to a mod like Pyanodon or Krastorio2
2. Click on recipes

**Expected behavior**
The recipe menu be in front of the scroll bar so the mouse wont interact with and scroll down a menu that you are not using

 - OS: Widows 10
 - Browser Microsoft Edge
 - Version 85.0.564.51

**Comment by dcbroad3** [comment] 2020-09-19 10:51
If I understand you correctly, what you're saying is that when the recipes menu is open (and large enough to have a scrollbar) you don't want it to be possible to scroll any other scrollbars on the page at all?
I ask because it sounds like you're describing the expected behavior. If you scroll the mouse outside the recipes menu it's expected that it will scroll the whole settings menu. 
Could you provide some more details? Does this cause part of the app to become unusable? Could you provide a screenshot of what seems to be broken?

**Comment by Kazmodah** [comment] 2020-09-19 17:10
![1](https://user-images.githubusercontent.com/54516305/93672895-822e0280-fa81-11ea-993e-9793737746b7.png)
Maybe it's something from Edge, because it seems to be something that more people would have found at that point

**Comment by dcbroad3** [comment] 2020-09-19 18:15
That's bizarre. This is the new edge with the swirl logo, right? It should be using the same rendering engine as chrome and i don't see the issue in chrome. If this is the old edge with the e logo then I don't consider that to be supported. 

Just checked and version 85 should be using the chrome rendering engine. I'll look into it and see if there's some way I can resolve this.

**Comment by dcbroad3** [comment] 2020-09-19 22:42
This issue doesn't appear in mobile chrome but apparently does appear in desktop chrome. Issue doesn't appear in desktop or mobile Firefox, which is how I missed it. Can't be resolved with a simple z-index update so this will take some effort to fix.

**Comment by dcbroad3** [comment] 2020-09-21 01:21
Was mistaken, found a simple z-index fix 😅

**Closed** 2020-09-21 01:23 UTC
Labels: bug
