### ISSUE TITLE
Fractionator/Proliferator bug

### ISSUE THREAD

**Issue by phoenixx-666** [factoriolab/factorio-lab#703] opened 2022-03-31 21:22 UTC
When I'm trying to change the Proliferator settings on the Franctionator, it gets replaced with Orbital Collector.

**Comment by dcbroad3** [comment] 2022-03-31 23:44
Could you share a link and some specific steps to reproduce this?

**Comment by phoenixx-666** [comment] 2022-04-01 12:38
[link](https://factoriolab.github.io/list?z=eJwrcIrSMjUwUEvyUCvWMtIyq3MyqnPyrXMKqXMKr3PKqnPKqXMqqnN2q3N2r.Ovi6iLrIuqS67LrqvQ0vLUQgXuamXGAOKmF-0_)

Change the proliferator settings in the fractionator to anything than nothing.
Tested in Firefox and Chromium

**Comment by dcbroad3** [comment] 2022-04-01 19:47
I can understand why this looks like a bug, but this is actually working as intended. 
The easiest way to look at what is happening is to look at the cost. The cost of the solution is shown in the very bottom left corner of the app. 
![image](https://user-images.githubusercontent.com/8430702/161330933-f9a5df85-350f-4c60-b91d-246007260d0d.png)
The cost of the original solution is 32274351.1.
When you switch to using proliferator, it switches to using the gas giant recipe, which has a cost of 32274858.47.
If you go to settings and disable the gas giant recipe (which I'm guessing is the desired solution to your issue), the using proliferator mk3 the cost goes up to 32645472.69.

The reason is that the cost formula weights increased input costs as more cumbersome than having extra buildings. Adding proliferator in that step means more proliferator is required, which increases the cost by more than the reduction in the number of fractionators reduces the cost. 

The solutions are likely either:

1. Disable the gas giant recipe in settings, if it is not a desired solution.
2. Increase the cost of factories, so that the proliferated fractionator solution is preferred. You can do this from the Matrix tab. If I increase the factory cost from 1 to 100, it prefers the fractionator recipe again:
![image](https://user-images.githubusercontent.com/8430702/161331524-e52c0553-542a-4a69-a327-7c2f21946b3c.png)

I hope this helps!

**Comment by dcbroad3** [comment] 2022-04-04 13:31
Hope this helped, closing the issue but let me know if it's still unclear.

**Closed by dcbroad3** 2022-04-04 13:31 UTC
Labels: bug
