### ISSUE TITLE
Power consumption does not appear to take modules into account.

### ISSUE THREAD

**Issue by AmericanPatriot6f0** [factoriolab/factorio-lab#240] opened 2020-10-22 22:19 UTC
Power consumption does not appear to take modules into account. 

For example, speed modules should add a 50% power consumption increase to both beacon and assembler.

**Comment by dcbroad3** [comment] 2020-10-22 22:49
I'm fairly sure this is working as intended. If you test this out when specifying one factory instead of a number of items the difference is more obvious. If you're specifying a number of items then the difference is less obvious because there is higher consumption per factory but fewer factories. 
To be clear the calculator doesn't include actual beacons power consumption; even though you specify a number of beacons per factory it's assumed there will be some amount of overlap in the beacon layout.

**Comment by dcbroad3** [comment] 2020-10-23 11:56
Closing this issue as this appears to be working in all my own testing. @AmericanPatriot6f0, if you're able to reproduce this issue, please provide specific URLs for the calculator that reproduce the buggy behavior.

**Closed by dcbroad3** 2020-10-23 11:56 UTC
Labels: bug
